# OrangeFox Configuration - MUST BE AT TOP (CORRECTED POSITION)
OF_TARGET_DEVICES := kansas
OF_USE_TWRP_SAR_DETECT := true
OF_NO_TREBLE_COMPATIBILITY_CHECK := true
OF_USE_LEGACY_BATTERY_SERVICES := 1
OF_FLASHLIGHT_ENABLE := 0
OF_ALLOW_DISABLE_NAVBAR := 1
OF_USE_SYSTEM_FINGERPRINT := 1
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 1
OF_KEEP_DM_VERITY := 1
OF_KEEP_VBMETA_FLAGS := 1
OF_SKIP_FBE_DECRYPTION := 1
OF_USE_LZ4_COMPRESSION := 1
OF_NO_RECOVERY_PARTITION := true  # CORRECTED VALUE (Newer Android 12+ devices use boot_a/boot_b for recovery)
OF_USE_NEW_MAGISKBOOT := 1
OF_QUICK_BACKUP_LIST := system vendor boot init_boot
OF_PATCH_AVB20 := 1
OF_STATUS_H := 85

# Device vendor/name
PRODUCT_DEVICE := kansas
PRODUCT_NAME := kansas
TARGET_DEVICE := kansas

# A/B Partition Configuration
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    boot \
    init_boot \
    vendor_boot \
    system \
    vendor \
    cache \
    mcf_ota

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

# Board (MEDIA-TEK SPECIFIC)
TARGET_BOARD_PLATFORM := mt6835
MTK_BOARD_PLATFORMS += mt6835
BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true
TARGET_BOOTLOADER_BOARD_NAME := kansas
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x07c08000
BOARD_SECOND_OFFSET := 0x00e88000
BOARD_TAGS_OFFSET := 0x0bc08000
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_SOURCE := kernel/motorola/kansas
TARGET_KERNEL_CONFIG := kansas_defconfig

# Partition Sizes (VERIFIED FOR MEDIA-TEK)
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_INIT_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_VENDORIMAGE_PARTITION_SIZE := 805306368
BOARD_CACHEIMAGE_PARTITION_SIZE := 402653184
BOARD_USERDATAIMAGE_PARTITION_SIZE := 55134117888
BOARD_MCF_OTA_PARTITION_SIZE := 1073741824

# File systems
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Android Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# Graphics
TW_THEME := portrait_hdpi
RECOVERY_SDCARD_ON_DATA := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_BRIGHTNESS_PATH := "/sys/class/backlight/aw99703-bl/brightness"
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 332
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_NTFS_3G := true
TW_USE_NEW_MINADBD := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_SCREEN_TIMEOUT := true

# MediaTek platform
BOARD_EGL_CFG := device/mediatek/common/egl.cfg
USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
TARGET_USES_HWC2 := true
TARGET_USES_GRALLOC1 := true
BOARD_USES_ADRENO := true

# MediaTek battery service fix
TW_BATTERY_SYSFS_PATH := "/sys/class/power_supply/battery"
TW_POWER_SYSTEMUI_TAP_TO_SHUTDOWN := true

# MediaTek touch panel fix
TW_INPUT_BLACKLIST := "hbtp_vm"

# Recovery key handling
TARGET_USES_HARDWARE_QCOM_KEYMASTER := false
TARGET_KEYMASTER_WAIT_FOR_QSEE := true
TARGET_PROVIDES_KEYMASTER := true

# Android 15 specific
PLATFORM_VERSION := 15
PLATFORM_SECURITY_PATCH := 2025-06-01
VENDOR_SECURITY_PATCH := 2025-06-01

# Critical Android 15 fixes
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
BUILD_BROKEN_VENDOR_PROPERTY_NAMESPACE := true
BUILD_BROKEN_ENFORCE_SYSPROP_OWNER := true
PRODUCT_SHIPPING_API_LEVEL := 35
PRODUCT_TARGET_VNDK_VERSION := 35
PRODUCT_EXTRA_VNDK_VERSIONS := 35
PRODUCT_ENFORCE_VINTF_MANIFEST := true

# Additional recovery features
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_PREPARE_DATA_MEDIA_EARLY := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXCLUDE_TWRPAPP := true
TW_INCLUDE_LEGACY_ADBBUSYBOX := true
